### ISSUE TITLE
improve display when no application

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/plugin-myapps#1]
**What type of your feature request?**  

- [ ] Add new features
- [x] Improve current features

**Describe the solution you'd like**  
It display blank when there no any applications, I think you should display a text **No any application now** for alternative

**Comment by zhaojing1987** [comment]
![image](https://github.com/Websoft9/plugin-myapps/assets/7624828/da15ab36-c277-4365-93bc-695f3ce309a5)
