### ISSUE TITLE
uninstall app Duplicati error 

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/plugin-myapps#27]
**Describe the bug**

![image](https://github.com/Websoft9/plugin-myapps/assets/16741975/162d127e-f892-4353-b423-f2be85d67f38)

This application is used **mount volume**

SOURCE_PATH="/var/lib/docker/volumes"
BACKUP_PATH="/data/websoft9/vl_backups"

```
    volumes:
      - config:/config
      - $SOURCE_PATH:/source  # mount to host diretory
      - $BACKUP_PATH:/backups
```

**Comment by qiaofeng1227** [comment]
other vm can not repeat this error
